aloha-agilex:
  file_path: "./assets/embodiments/aloha-agilex/"

piper:
  file_path: "./assets/embodiments/piper"

franka-panda:
  file_path: "./assets/embodiments/franka-panda/"

ARX-X5:
  file_path: "./assets/embodiments/ARX-X5"

ur5-wsg:
  file_path: "./assets/embodiments/ur5-wsg"

rm_Lifting_robot_65B_jaw_description:
  file_path: "./assets/embodiments/rm_Lifting_robot_65B_jaw_description"

rm65b:
  file_path: "./assets/embodiments/rm65b"

